{
 "title": "terraform metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pxt",
    "label": "pxt",
    "query": "SELECT DISTINCT pxt FROM terraformrun ORDER BY pxt;"
   }
  ]
 },
 "panels": [
  {
   "title": "Success and Failure count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \nSUM(CASE WHEN success = True THEN 1 ELSE 0 END) AS Success_count, \nSUM(CASE WHEN success = false THEN 1 ELSE 0 END) AS fail_count, \navg(success::int)*100 AS success_ratio\nFROM terraformrun\nwhere pxt = '${pxt}';"
    }
   ]
  },
  {
   "title": "Avg terraform run time in sec",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \navg(total_time) as avg_terraform_run_time_in_sec\nFROM terraformrun\nwhere pxt = '${pxt}';"
    }
   ]
  },
  {
   "title": "Total Terraform Run Success Ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \nSUM(CASE WHEN success = True THEN 1 ELSE 0 END) AS Success_count, \nSUM(CASE WHEN success = false THEN 1 ELSE 0 END) AS fail_count, \navg(success::int)*100 AS success_ratio\nFROM terraformrun;"
    }
   ]
  },
  {
   "title": "Number of created, updated & deleted resources",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(CASE WHEN r.action IN ('create', 'created') THEN 1 END) AS create_count,\n  COUNT(CASE WHEN r.action IN ('update', 'updated') THEN 1 END) AS update_count,\n  COUNT(CASE WHEN r.action IN ('delete', 'deleted') THEN 1 END) AS delete_count\nFROM resources r\nJOIN terraformRun tr ON r.terraform_run_id = tr.id\nWHERE tr.pxt = '${pxt}'\nGROUP BY tr.pxt\nORDER BY tr.pxt;\n"
    }
   ]
  },
  {
   "title": "All PXTs Avg terraform run time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \n  pxt, \n  AVG(total_time) AS avg_total_time\nFROM terraformrun\nGROUP BY pxt;\n"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT failed_resource\nFROM terraformrun, unnest(failed_resources) AS failed_resource\nWHERE pxt = '${pxt}'\n  AND failed_resource <> '{}';\n"
    }
   ]
  },
  {
   "title": "Terraform Run success Ratio per PXT",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \n  pxt,\n  SUM(CASE WHEN success = true THEN 1 ELSE 0 END) AS success_count,\n  SUM(CASE WHEN success = false THEN 1 ELSE 0 END) AS fail_count,\n  AVG(success::int) * 100 AS success_ratio\nFROM terraformrun\nGROUP BY pxt;\n"
    }
   ]
  },
  {
   "title": "Most Updated Resource per PXT",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT resource_name, resource_type, COUNT(*) AS update_count, avg(total_time) as avg_updation_time \nFROM resources\nWHERE action = 'update' AND\nterraform_run_id IN ( \n  SELECT id FROM terraformrun WHERE pxt='${pxt}'\n )\nGROUP BY resource_name, resource_type\nORDER BY update_count DESC;"
    }
   ]
  },
  {
   "title": "Resources in every PXT",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "-- SELECT \n--   tr.pxt,\n--   r.resource_name,\n--   r.resource_type\n-- FROM resources r\n-- JOIN terraformrun tr ON r.terraform_run_id = tr.id\n-- GROUP BY tr.pxt, r.resource_type\n-- order by tr.pxt, r.resource_type, resource_name;\n\n-- SELECT \n--   tr.pxt,\n--   r.resource_name,\n--   COUNT(DISTINCT r.resource_type) AS unique_resources\n-- FROM resources r\n-- JOIN terraformrun tr ON r.terraform_run_id = tr.id\n-- GROUP BY tr.pxt, r.resource_name\n-- ORDER BY tr.pxt, r.resource_name;\n\nSELECT \n  tr.pxt,\n  r.resource_name,\n  ARRAY_AGG(DISTINCT r.resource_type ORDER BY r.resource_type) AS resources\nFROM resources r\nJOIN terraformrun tr ON r.terraform_run_id = tr.id\nGROUP BY tr.pxt, r.resource_name\nORDER BY tr.pxt, r.resource_name;\n\n\n\n"
    }
   ]
  },
  {
   "title": "errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT error_messages from errors where terraform_run_id IN (SELECT id FROM terraformrun WHERE pxt='${pxt}')"
    }
   ]
  },
  {
   "title": "All Resources per PXT",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT \n  resource_type,\n  resource_name,\n  AVG(total_time) AS avg_total_time\nFROM resources\nWHERE terraform_run_id IN (\n  SELECT id \n  FROM terraformrun \n  WHERE pxt = '${pxt}'\n)\nGROUP BY resource_type, resource_name;\n"
    }
   ]
  },
  {
   "title": "Updated Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "-- SELECT \n--   r.resource_type,\n--   r.resource_name\n-- FROM resources r\n-- JOIN terraformrun tr ON r.terraform_run_id = tr.id\n-- WHERE tr.pxt = '${pxt}'\n--   AND r.action IN ('update', 'updated')\n-- ORDER BY tr.pxt, r.resource_type, r.resource_name;\n\n\n-- SELECT \n--   r.resource_type,\n--   r.resource_name,\n--   AVG(r.total_time) AS avg_total_time\n-- FROM resources r\n-- JOIN terraformrun tr ON r.terraform_run_id = tr.id\n-- WHERE tr.pxt = '${pxt}'\n--   AND r.action IN ('update', 'updated')\n-- GROUP BY r.resource_type, r.resource_name\n-- ORDER BY r.resource_type, r.resource_name;\n\n\nSELECT \n  resource_type,\n  resource_name,\n  AVG(total_time) AS avg_updation_time\nFROM resources\nWHERE terraform_run_id IN (\n  SELECT id \n  FROM terraformrun \n  WHERE pxt = '${pxt}'\n) and action in ('updated', 'update')\nGROUP BY resource_type, resource_name;\n\n"
    }
   ]
  },
  {
   "title": "Deleted Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "-- SELECT \n--   r.resource_type,\n--   r.resource_name\n-- FROM resources r\n-- JOIN terraformrun tr ON r.terraform_run_id = tr.id\n-- WHERE tr.pxt = '${pxt}'\n--   AND r.action = 'delete'\n-- ORDER BY tr.pxt, r.resource_type, r.resource_name;\n\n\nSELECT \n  resource_type,\n  resource_name,\n  AVG(total_time) AS avg_deletion_time\nFROM resources\nWHERE terraform_run_id IN (\n  SELECT id \n  FROM terraformrun \n  WHERE pxt = '${pxt}'\n) and action in('deleted', 'delete')\nGROUP BY resource_type, resource_name;\n\n"
    }
   ]
  },
  {
   "title": "Created Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT \n  resource_type,\n  resource_name,\n  AVG(total_time) AS avg_total_time\nFROM resources\nWHERE terraform_run_id IN (\n  SELECT id \n  FROM terraformrun \n  WHERE pxt = '${pxt}'\n) and action IN ('created', 'create')\nGROUP BY resource_type, resource_name;\n"
    }
   ]
  }
 ]
}